# src/main/resources/application.yml

spring:
  application:
    name: jukeanator-engine

song-library:
  repository-type: filesystem   # filesystem | postgres
  #root-path: R:\\Rock_On_Third # windows
  root-path: /mnt/readyNAS/Rock_On_Third # linux
  requires-metadata: false
  use-genre: true
  use-top-folder-for-genre: true

  discogs:
    consumer-key: vBSFEvNtGflHQnULBNnL
    consumer-secret: AOOYhlvSshYkJieLRrdTCUoLcsWACfWW
    
song-queue:
  repository-type: filesystem   # filesystem | postgres
  #root-path: R:\\Rock_On_Third # windows
  root-path: /mnt/readyNAS/Rock_On_Third # linux
  
song-player:  
  player-type: vlc   # vlc (all operating systems) | winamp (windows only)

user-interface:
  enabled: true   # if true, a JFC/Swing UI is launched, otherwise, a headless backend      
  baseUrl: http://localhost:8080
