JukeANator Properties (Build: 06-27-2019)
SerialNumber=D4-81-D7-E5-8E-96
-----------------------
Country=US
Language=en
DefaultCountry=US
DefaultLanguage=en
DynamicEnglishSpanish=false
-----------------------
AlwaysOnTop=false
ShowQueued=false
EnableSingleClickSelection=true
ShowConfirmation=true
ShowPriority=true
EnableProgressiveSongPriority=false
EnableWholeAlbumSelection=false
EnableAllArtistsSlider=false
EnableCdTitleReleaseDateSorting=false
ShowSplashScreen=true
UseTypeAheadSearch=true
UseScreenSaver=false
ScreenSaverType=commercial
ScreenSaverThresholdUseMinutes=true
UseSecondaryDisplayContentPlayer=false
UseNewCDsForScreenSaver=false
ScreenSaverThreshold=1
ScreenSaverInterval=20
GrabFocusOnStartup=true
ShowNewCdsByDefaultOnPopularScreen=true
HasDualDisplay=false
UseEntireScreen=true
ShowCoverArtOnDetachedSongPlayers=false
UseBigScrollBars=true
UnzipKaraokeZip=true
KaraokeMode=false
AskNameForKaraoke=false
HideKaraokeExitBtn=false
EnableEnhancedKaraokeMode=false
EnableNirCmdForLineInVolume=false
ExclusiveMode=true
DisableAdminScreenToggle=false
DisplaySongFirstOnCompilation=true
RenderQueueColorsByGenre=false
HideNumberBtns=true
ShowNextBtn=true
ShowEnableQueuedSongListDialog=false
EnableVetoBtn=false
CreditsPerVeto=3
EnableShowCdPanelDialog=false
CdPanelDialogSongFontSize=16
SongFontName=SansSerif
SongFontSize=12
SecondaryDisplayX=1024
SecondaryDisplayY=0
SecondaryDisplayWidth=1024
SecondaryDisplayHeight=768
PatentLabelText=(c) 2000 Digital Jukebox Technologies LLC. All Rights Reserved.
InfoLabelText=E-mail comments/suggestions to Tom Myers at:  tmyers1@yahoo.com
Level_0=0
Level_1=5
Level_2=10
NewCDVectorSize=100
NewCDAgeThreshold=120
NewSongVectorSize=100
AllVectorSize=500
SearchVectorSize=200
AdminButtonVisible=true
SearchButtonVisible=true
PopularButtonVisible=true
StyleButtonVisible=true
ShowCurrentButtonVisible=true
BackButtonVisible=true
TopButtonVisible=true
PrevGenreButtonVisible=true
NextGenreButtonVisible=true
BottomButtonVisible=true
AllArtistsSliderVisible=true
AllArtistsButtonArrayVisible=false
ThumbPauseButtonVisible=true
ThumbNextButtonVisible=true
ThumbIncrementButtonVisible=true
ThumbDecrementButtonVisible=true
-----------------------
NumberToQueue=0
RandomPlay=false
RandomPlayInterval=20
EnableRandomPlayDuration=false
RandomPlayDurationBegin=8
RandomPlayDurationEnd=17
FlipToRandom=true
PerformExcludesOnSongQueue=false
RandomSongExcludedGenres=
RandomSongExcludedArtists=
RandomByPlayList=false
UseRandomSongPlayThreshold=false
RandomByPlayListThreshold=1
RandomPlayListFilePath=Top50Songs.PL
RandomByGenre=false
RandomByCD=false
-----------------------
ReceiveRemoteCommandPort=7095
UseWebServer=false
WebServerPort=80
AuthorizedWebClients=127.0.0.1
AuthorizedAdminWebClients=127.0.0.1
UseRemoteDataSource=false
PrefetchForRemoteDataSource=true
RemoteDataSourceBuffer=4096
RemoteDataSourceUrl=www.jukeanator.com/demo
CurrentSongListTimestamp=0
AdditionalCreditsForDownload=5
-----------------------
PlayerVolume=75
MasterVolume=80
UseLowPrioritySongVolume=false
LowPrioritySongVolume=45
WaveVolume=80
LineInVolume=60
BetweenSongsDelaySeconds=0
LineInDelaySeconds=30
-----------------------
MaximumConsecutiveSongPlaysByArtist=1000
MinimumMinutesBetweenSongPlays=0
UseGenreSongPlayRestrictions=false
SongPlayLimitOverridePattern=L,L,R,L,L
-----------------------
PlayExplicitSongs=true
AllowExplicitLyricsBegin=5
AllowExplicitLyricsEnd=5
MaxQueueSize=1000
MaxPauseMinutes=30
RemoveDuplicatesFromPlaylists=false
PerformFlushUponHibernation=true
SavePlayedSongsToFile=false
SongPlayer=com.djt.jukeanator.player.WinAmpMgr
SecondarySongPlayers=
VLCLocation=C:/Program Files/VideoLAN/VLC
EnableVLCOptions=false
VLCOptions=--force-dolby-surround=2,--hq-resampling,--volume=100,--norm-buff-size=20,--norm-max-level=1.60,--audio-filter=normvol:compressor,--no-video-title-show,--equalizer-bands=8.9 10.5 10.3 6.2 8.4 10.3 13 12.2 10.3 7,--equalizer-preamp=12
WinampLocation=winamp.exe
ShowWinampSecondaryDisplay=false
KodiServerHostname=localhost
KodiServerPort=8080
KodiUsername=kodi
KodiPassword=password
VlcServerHostname=localhost
VlcServerPort=8080
VlcUsername=
VlcPassword=password
com.djt.jukeanator.player.WinAmpMgr.FileTypes=.mp3,.wav,.cda,.flc,.flac
com.djt.jukeanator.player.WinAmpMgr.VideoFileTypes=
com.djt.jukeanator.player.VlcMgr.FileTypes=.mp3,.wav,.cda,.flc,.flac,.wma,.oma,.m4p,.aac,.m4a,.m4b
com.djt.jukeanator.player.VlcMgr.VideoFileTypes=
com.djt.jukeanator.player.DetachedVlcMgr.FileTypes=.mp3,.wav,.cda,.flc,.flac,.wma,.oma,.m4p,.aac,.m4a,.m4b
com.djt.jukeanator.player.DetachedVlcMgr.VideoFileTypes=.mpg,.mpeg,.flv,.avi,.wmv,.asf,.mov,.mp4,.divx,.3gp
com.djt.jukeanator.player.KodiMgr.FileTypes=.mp3,.wav,.cda,.flc,.flac,.wma,.oma,.m4p,.aac,.m4a,.m4b
com.djt.jukeanator.player.KodiMgr.VideoFileTypes=
com.djt.jukeanator.player.VlcHttpMgr.FileTypes=.mp3,.wav,.cda,.flc,.flac,.wma,.oma,.m4p,.aac,.m4a,.m4b
com.djt.jukeanator.player.VlcHttpMgr.VideoFileTypes=.mpg,.mpeg,.flv,.avi,.wmv,.asf,.mov,.mp4,.divx,.3gp,.vob,.ogg
-----------------------
EnableHibernation=false
HibernateBegin=3
HibernateEnd=14
-----------------------
EnableFreePlay=false
FreePlayBegin=9
FreePlayEnd=15
UnlimitedCredits=false
NumDailyFreeCredits=24
BillAcceptor=pulse
CreditsPer=3
NumQuartersPerCredit=2
ChargeExtraCreditForVideo=false
credits=2147483647
BonusFactor_0=0
BonusFactor_1=5
BonusFactor_2=10
BonusFactor_3=20
BonusFactor_4=50
EnableAcceptorCountReset=false
UseDecay=true
DecayThreshold=3
-----------------------
AcceptorPulsesPerDollar=1
AcceptorIncrementThresholdMillis=1000
AcceptorIncrementOnesKey=a
AcceptorIncrementQuartersKey=*
-----------------------
AcceptorPort=COM1
AcceptorPoll=500
AcceptOnes=true
AcceptTwos=true
AcceptFives=true
AcceptTens=false
AcceptTwentys=false
AcceptFiftys=false
AcceptHundreds=false
-----------------------
EnableKeyboardMappings=true
PlayerVolumeUpKey=*
PlayerVolumeDownKey=*
PlayerPauseKey=p
PlayerRejectKey=r
PlayerHibernateKey=*
PlayerWakeupKey=*
LockQueueKey=*
UnlockQueueKey=*
BackButtonKey=*
SearchButtonKey=*
PopularButtonKey=*
StyleButtonKey=*
TopButtonKey=*
PrevGenreButtonKey=*
NextGenreButtonKey=*
BottomButtonKey=*
PrevButtonKey=*
NextButtonKey=*
OneButtonKey=*
TwoButtonKey=*
ThreeButtonKey=*
FourButtonKey=*
FiveButtonKey=*
SixButtonKey=*
SevenButtonKey=*
EightButtonKey=*
NineButtonKey=*
ZeroButtonKey=*
EnterButtonKey=*
EnglishSpanishButtonKey=*
UpButtonKey=*
DownButtonKey=*
CloseButtonKey=*
OKButtonKey=*
YesButtonKey=*
CancelButtonKey=*
ScrollCdPanelUpKey=*
ScrollCdPanelDownKey=*
DeleteSongKey=*
-----------------------
SuppressFileChooserDialogOnRescan=false
ScanPaths=C:\kiosk\Demo_Music
UseTopFoldersForGenre=false
UseID3TagsForGenre=false
ReadID3TagsOnRescan=true
IgnorePaths=
CopyNewContent=false
NewContentPath=E:
CdDvdRomPath=
EnableAutomaticUpdates=true
TreeSaveInterval=1
SongCopierDestination=G:\
SongCopierUseFolders=true
SongCopierUseNumberPrefix=true
-----------------------
CompressDataFiles=false
DebugMode=false
DemoteToNonCommercial=false
AutoProvisionEmail=
AutoProvisionPasscode=
UseLogFile=false
-----------------------
LocationName=
ASCAPAccountNumber=
BMIAccountNumber=
SESACAccountNumber=
CustomerEmail=
CustomerName=
AmazonAffiliateId=
AmazonAwsAccessKeyId=
AmazonAwsSecretKey=
LastFmSecretKey=
